# Generated by Django 6.0.7 on 2026-07-30 22:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='event',
            name='outcome_notes',
            field=models.TextField(blank=True, help_text='Notes about how the event went'),
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('organized', 'Organized'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='events.event')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='EventParticipant',
        ),
    ]
