# Generated by Django 6.0.7 on 2026-07-31 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_max_participants_event_outcome_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for cancelling this event'),
        ),
    ]
