# Generated by Django 6.0.7 on 2026-07-30 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('is_editable', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
