# Generated by Django 6.0.7 on 2026-07-30 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('board', 'Board Member'), ('treasurer', 'Treasurer'), ('manager', 'Manager'), ('member', 'Member')], default='member', max_length=20),
        ),
    ]
