# Generated by Django 6.0.7 on 2026-07-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_member_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='due_day',
        ),
    ]
