# Generated by Django 6.0.7 on 2026-08-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_member_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram user ID for bot linking', null=True, unique=True),
        ),
    ]
