# Generated by Django 6.0.7 on 2026-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='telegram_link_code',
            field=models.CharField(blank=True, help_text='Temporary code for linking Telegram', max_length=8, null=True),
        ),
    ]
